 [profile.default]
src = "contracts"
out = "../metadata"            
libs = ["lib"]
solc = '0.8.23'                
evm_version = 'shanghai'       
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
via_ir = true
eth_rpc_url = "${HEDERA_RPC_URL}"

[rpc_endpoints]
hedera = "${HEDERA_RPC_URL}"
 